---
- hosts: all
  tasks:
    - name: Set authorized key taken from file
      authorized_key:
        user: "{{ansible_user}}"
        state: present
        key: "{{ lookup('file', '/home/sane4eg/.ssh/id_rsa.pub') }}"
