---
- name: install docker
  apt:
    name: "docker.io"
    state: present

- name: set cgroupdriver=systemd
  copy:
    src: '{{role_path}}/files/daemon.json'
    dest: /etc/docker/daemon.json
    mode: 0644

- name: Enable and check Docker service
  systemd:
    name: docker
    daemon_reload: yes
    state: started
    enabled: yes
